# Generated by Django 5.2.6 on 2025-11-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_remove_booking_service_remove_booking_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barber.staff'),
        ),
    ]
